#pragma config(Motor,  port1,           lLift,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rLift,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		if(vexRT[Btn5U])
			motor[lLift] = 127;
		else if(vexRT[Btn5D])
			motor[lLift] = -127;
		else
			motor[lLift] = 0;
		if(vexRT[Btn6U])
			motor[rLift] = 127;
		else if(vexRT[Btn6D])
			motor[rLift] = -127;
		else
			motor[rLift] = 0;
	}
}
