#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    liftPot,        sensorNone)
#pragma config(Sensor, in2,    goalPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  lDriveEnc,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rDriveEnc,      sensorQuadEncoder)
#pragma config(Motor,  port1,           roller,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rLift,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lLift,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frDrive,       tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           brDrive,       tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           ylDrive,       tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           mrDrive,       tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port8,           mlDrive,       tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port9,           lGoal,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rGoal,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true) {
		motor[ylDrive] =
			motor[mlDrive] =
			vexRT[Ch3] + vexRT[Ch1];

		motor[frDrive] =
			motor[mrDrive] =
			motor[brDrive] =
			vexRT[Ch3] - vexRT[Ch1];

		motor[lLift] =
			motor[rLift] =
			(vexRT[Btn5U] ^ vexRT[Btn5D])
				? (vexRT[Btn5U])
					? 127
					: -127
				: 0;

		motor[lGoal] =
			motor[rGoal] =
			(vexRT[Btn6U] ^ vexRT[Btn6D])
				? (vexRT[Btn6U])
					? 127
					: -127
				: 0;

		motor[roller] =
			(vexRT[Btn7U] ^ vexRT[Btn7D])
				? (vexRT[Btn7U])
					? 127
					: -127
				: 0;

		wait1Msec(20);
	}

}
